# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aktif', models.BooleanField(default=1)),
                ('Name', models.CharField(max_length=250, verbose_name='Name')),
                ('Surname', models.CharField(max_length=250, verbose_name='Name')),
                ('Joined', models.DateField(default=django.utils.timezone.now, verbose_name='Joined on')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=1)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(max_length=3500, verbose_name='Content')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('postauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
